In [72]:
import csv
import numpy as np
import numpy.linalg as LA
import matplotlib.pyplot as plt
import seaborn as sns

data=np.loadtxt("sample.csv",delimiter=",",dtype=float)

Cov=np.cov(data.T)      #   np.covの実装が、(m,n)型行列の入力を(n,m)型の行列と解釈するようなので、本来の意味に戻すため.Tで転置
eigen = LA.eig(Cov)      #   固有値と固有ベクトル　　


print("{0}\n の主成分分析\n".format(data))

print("固有値は大きい順に")
for i in range(len(eigen[0])):
    print(eigen[0][i])

    
print("\n それに対応する固有ベクトルは")
for i in range(len(eigen[0])):
    print(eigen[1][i] )
    
    
Principal=np.dot(data[0],eigen[1][0])

for i in range(data.shape[0]):
    print("\n 特に{0}に対する第一主成分得点は{1}".format(data[i],np.dot(data[i],eigen[1][0])))        

#  一番大きい固有値に対応する固有ベクトルとの内積をとっている = 射影


for i in range(data.shape[0]):
    print("\n 特に{0}に対する第二主成分得点は{1}".format(data[i],np.dot(data[i],eigen[1][1])))        


    
 
# 以下、プロットする方法(射影したあとの2次元座標のペアをまとめて代入する方法がわからない。。。)

# for i in range(data.shape[0]):
#     data_proj=[]
#     data_proj[i].append([np.dot(data[i],eigen[1][0]),np.dot(data[i],eigen[1][1])])

    
# print(data_proj)


[[  3.   2.   7.   8.]
 [  5.  11.   1.   5.]
 [ 13.   4.   2.   3.]]
 の主成分分析

固有値は大きい順に
38.7915026221
28.2084973779
-1.80246908085e-15
-7.23895176383e-16

 それに対応する固有ベクトルは
[-0.74550218 -0.47783385  0.01527459 -0.23354332]
[-0.28140848  0.82633094 -0.26847332 -0.44372736]
[ 0.44967437 -0.29707011 -0.71839675 -0.84230005]
[ 0.4035204   0.02452211  0.6415566   0.19772245]

 特に[ 3.  2.  7.  8.]に対する第一主成分得点は-4.953598714480895

 特に[  5.  11.   1.   5.]に対する第一主成分得点は-10.136125331416668

 特に[ 13.   4.   2.   3.]に対する第一主成分得点は-12.272944599655238

 特に[ 3.  2.  7.  8.]に対する第二主成分得点は-4.620695706080976

 特に[  5.  11.   1.   5.]に対する第二主成分得点は5.195487793113569

 特に[ 13.   4.   2.   3.]に対する第二主成分得点は-2.2211152243478716
